### ISSUE TITLE
Provider

### ISSUE THREAD

**Issue by 9renpoto** [userdive/agent.js#106]
like google analytics

**Comment by shoota** [comment]
### Google Analytics Usage
https://developers.google.com/analytics/devguides/collection/analyticsjs/using-plugins

### Example Plugin
https://github.com/googleanalytics/autotrack

**Comment by shoota** [comment]
API Examples that it should implement

## require

`('[trackerName.]require', pluginName, [pluginOptions]): undefined`
https://developers.google.com/analytics/devguides/collection/analyticsjs/command-queue-reference#require


## provide

`('provide', pluginName, pluginConstuctor)`
https://developers.google.com/analytics/devguides/collection/analyticsjs/command-queue-reference#provide
