### ISSUE TITLE
cross domain tracking

### ISSUE THREAD

**Issue by 9renpoto** [userdive/agent.js#117]
with query paramater

**Comment by shoota** [comment]
- [Cross-domain tracking in GA](https://developers.google.com/analytics/devguides/collection/analyticsjs/cross-domain)
- [linker plugin](https://developers.google.com/analytics/devguides/collection/analyticsjs/linker)

### at src domain site
```javascript
ga('require', 'linker');
// ga('[trackerName.]linker:autoLink', domains, [useAnchor], [decorateForms]);
ga('linker:autoLink', ['destination.com'], false, true);
```

### at destination domain site
```javascript
ga('create', 'UA-XXXXX-Y', 'auto', {allowLinker: true});
```
